source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
timezone:    nil
encoding:    utf-8

safe: true
lsi:  false
pygments: true
